services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    restart: always
    command:
      - start
      - -A
      - --auth
      - --user=dev
      - --pass=dev
      - file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - data:/data

volumes:
  data:
