services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_PASSWORD: root
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
    ports:
      - "5656:5656"
    volumes:
      - data:/var/lib/edgedb/data

volumes:
  data:
