services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    ports:
      - "5656:5656"
    volumes:
      - data:/var/lib/edgedb/data

volumes:
  data:
