services:
  keydb:
    container_name: keydb
    image: eqalpha/keydb:latest
    restart: always
    command: keydb-server --requirepass dev --storage-provider flash /flash
    ports:
      - 6379:6379
    volumes:
      - data:/flash

volumes:
  data:
