version: "3.8"

services:
  tembo:
    image: quay.io/tembo/tembo-local
    restart: always
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    volumes:
      - data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  data:
