services:
  authorizer:
    image: lakhansamani/authorizer:latest
    container_name: authorizer
    restart: always
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://dev:dev@host.docker.internal:5432/authorizer
