services:
  authorizer:
    image: lakhansamani/authorizer:latest
    ports:
      - "8070:8080"
    restart: always
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://root:root@host.docker.internal:5432/authorizer
