services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: mysql
      DATABASE_URL: dev:dev@tcp(host.docker.internal:3306)/authorizer

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
