services:
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    restart: always
    environment:
      PGRST_DB_URI: postgresql://dev:dev@host.docker.internal:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: public
    ports:
      - 3000:3000

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      API_URL: http://localhost:3000/
    ports:
      - 8080:8080
    expose:
      - 8080
