services:
  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgresql://root:root@host.docker.internal:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: public

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
