services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:latest
    restart: always
    depends_on:
      - mssql
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: sqlserver
      DATABASE_URL: sqlserver://SA:dev@host.docker.internal:1433?database=authorizer

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: dev
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql/data
      - data:/var/opt/mssql/log

volumes:
  data:
