version: "3"
services:
  authorizer:
    image: lakhansamani/authorizer
    ports:
      - "8070:8080"
    restart: always
    environment: 
      DATABASE_TYPE: sqlserver
      DATABASE_URL: sqlserver://SA:Arkam2004@host.docker.internal:1433?database=authorizer
      REDIS_URL: redis://host.docker.internal:6379