services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: mongodb
      DATABASE_URL: mongodb://dev:dev@host.docker.internal:27017

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - 27017:27017
    volumes:
      - data:/db

volumes:
  data:
