services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:latest
    restart: always
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: mongodb
      DATABASE_URL: mongodb://dev:dev@host.docker.internal:27017
