services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: openfga/openfga:latest
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://dev:dev@postgres:5432/postgres?sslmode=disable
    command: migrate
    networks:
      - default

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://dev:dev@postgres:5432/postgres?sslmode=disable
    command: run
    ports:
      - 8080:8080
      - 8081:8081
      - 3000:3000
    networks:
      - default

volumes:
  data:
