services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:latest
    restart: always
    depends_on:
      - cassandra
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: cassandradb
      DATABASE_URL: host.docker.internal:9042
      DATABASE_USERNAME: cassandra
      DATABASE_PASSWORD: cassandra

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    restart: always
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
      - 9042:9042
    volumes:
      - data:/var/lib/cassandra

volumes:
  data:
