version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: arkam
      POSTGRES_PASSWORD: Arkam2004
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
