services:
  arroyo:
    image: ghcr.io/arroyosystems/arroyo-single:latest
    container_name: arroyo
    restart: always
    environment:
      CHECKPOINT_URL: /checkpoint
      ARTIFACT_URL: /artifact
    ports:
      - 8002:8000
    volumes:
      - data:/var/lib/postgresql/data
      - data:/checkpoint
      - data:/artifact

volumes:
  data:
