services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:latest
    restart: always
    ulimits:
      memlock: -1
    depends_on:
      - valkey
    command: centrifugo -c config.json
    ports:
      - 9000:9000
    volumes:
      - ./config.json:/centrifugo/config.json

  valkey:
    container_name: valkey
    image: valkey/valkey:latest
    restart: always
    command: valkey-server --requirepass dev --save 60 1 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data:
