services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:latest
    restart: always
    ulimits:
      memlock: -1
    command: centrifugo -c config.json
    ports:
      - 9000:9000
    volumes:
      - ./config.json:/centrifugo/config.json
