services:
  authorizer:
    image: lakhansamani/authorizer:latest
    restart: always
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: sqlserver
      DATABASE_URL: sqlserver://SA:dev@host.docker.internal:1433?database=authorizer
      REDIS_URL: redis://host.docker.internal:6379
