services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ferretdb
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    container_name: ferretdb
    restart: always
    depends_on:
      - postgres
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://dev:dev@postgres:5432/ferretdb
    ports:
      - 27017:27017

volumes:
  data:
