services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: dev
      RABBITMQ_DEFAULT_USER: dev
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq
    volumes:
      - data:/var/lib/rabbitmq/
      - log:/var/log/rabbitmq

networks:
  rabbitmq:

volumes:
  data:
  log:
