services:
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq_data:
  rabbitmq_log:
