services:
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: dev
      RABBITMQ_DEFAULT_USER: dev
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq_data:
  rabbitmq_log:
