services:
  dragonflydb:
    container_name: dragonflydb
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    restart: always
    ulimits:
      memlock: -1
    command: dragonfly --requirepass dev --save 60 1
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data:
