services:
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://root:root@host.docker.internal:5432/postgres?sslmode=disable
