services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: dev
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql/data
      - data:/var/opt/mssql/log

volumes:
  data:
