services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: dev
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
