services:
  tembo:
    container_name: tembo
    image: quay.io/tembo/tembo-local:latest
    restart: always
    stdin_open: true
    tty: true
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
