services:
  tembo:
    image: quay.io/tembo/tembo-local
    restart: always
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    volumes:
      - data:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]

volumes:
  data:
