services:
  typesense:
    container_name: typesense
    image: typesense/typesense:26.0
    restart: always
    command: --data-dir /data --api-key=dev --enable-cors
    ports:
      - 8108:8108
    volumes:
      - data:/data

volumes:
  data:
