services:
  typesense:
    image: typesense/typesense:26.0
    restart: always
    command: --data-dir /data --api-key=xyz --enable-cors
    ports:
      - 8108:8108
    volumes:
      - ./typesense-data:/data
