services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    restart: always
    command:
      - start
      - -A
      - --auth
      - --user=dev
      - --pass=dev
      - file:/data/database.db
    volumes:
      - data:/data

volumes:
  data:
