version: "3"
services:
  authorizer:
    image: lakhansamani/authorizer
    ports:
      - "8050:8050"
    restart: always
    environment:
      PORT: 8050
      DATABASE_TYPE: sqlite
      DATABASE_URL: data.db
