cacheConfig:
  conn: ""
  defaultTTL: 0
  enabled: false
clusterConfig:
  enableTelemetry: false
  letsencryptEmail: ""
integrations: {}
integrationsHooks: {}
projects: {}
ssl:
  crt: ""
  enabled: false
  key: ""
