services:
  spicedb:
    image: authzed/spicedb:latest
    container_name: spicedb
    restart: always
    depends_on:
      - migrate
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: foobar
      SPICEDB_DATASTORE_ENGINE: cockroachdb
      SPICEDB_DATASTORE_CONN_URI: postgresql://dev:dev@cockroachdb:26257/spicedb?sslmode=disable
      SPICEDB_LOG_LEVEL: info
      SPICEDB_LOG_FORMAT: console
    command: serve
    ports:
      - 8080:8080
      - 9090:9090
      - 50051:50051

  migrate:
    image: authzed/spicedb:latest
    container_name: migrate
    restart: on-failure:3
    depends_on:
      - init_database
    environment:
      SPICEDB_DATASTORE_ENGINE: cockroachdb
      SPICEDB_DATASTORE_CONN_URI: postgresql://dev:dev@cockroachdb:26257/spicedb?sslmode=disable
      SPICEDB_LOG_LEVEL: info
      SPICEDB_LOG_FORMAT: console
    command: migrate head

  cockroachdb_1:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb_1
    restart: on-failure:3
    depends_on:
      - cockroachdb_2
    environment:
      COCKROACH_HOST: cockroachdb:26257
    command: "sql --insecure -e 'CREATE DATABASE IF NOT EXISTS spicedb;'"

  cockroachdb_2:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb_2
    restart: on-failure:3
    depends_on:
      - cockroachdb_3
    environment:
      # initialize cluster through node 1
      COCKROACH_HOST: cockroachdb_1:26257
    command: "init --insecure"

  cockroachdb_3:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb_3
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
    command: "start --join=cockroachdb_1,cockroachdb_2,cockroachdb_3 --insecure"
    ports:
      - 8080
      - 26257
    healthcheck:
      test: "curl --fail http://localhost:8080/health?ready=1 || exit 1"
      interval: "2s"
      retries: 3
      start_period: "15s"
      timeout: "5s"
