services:
  authorizer:
    restart: always
    image: lakhansamani/authorizer:latest
    ports:
      - 8050:8050
    environment:
      PORT: 8050
      DATABASE_TYPE: sqlite
      DATABASE_URL: data.db
