services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: always
    command: valkey-server --requirepass dev --save 60 1 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data:
