services:
  scylladb:
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9180:9180"
    volumes:
      - data:/var/lib/scylla

volumes:
  data:
