services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: arkam
      MINIO_ROOT_PASSWORD: Arkam2004
    command: server --console-address ":9001" /data

volumes:
  minio_data:
