services:
  scylladb:
    image: cassandra:latest
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
      - "9042:9042"
    volumes:
      - data:/var/lib/cassandra

volumes:
  data:
