services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    restart: always
    command:
      - start
      - --user=dev
      - --pass=dev
      - memory
    ports:
      - 8000:8000
