services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160
      - 4161
  nsqd:
    image: nsqio/nsq
    depends_on:
      - nsqlookupd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - 4150
      - 4151
  nsqadmin:
    image: nsqio/nsq
    depends_on:
      - nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - 4171
