services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    image: nsqio/nsq
    depends_on:
      - nsqlookupd
    command: /nsqd -data-path /usr/local/nsq/bin --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - 4150:4150
      - 4151:4151
    volumes:
      - data:/usr/local/nsq/bin

  nsqadmin:
    image: nsqio/nsq
    depends_on:
      - nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - 4171:4171

volumes:
  data:
