services:
  authorizer:
    image: lakhansamani/authorizer:latest
    ports:
      - "8070:8080"
    restart: always
    environment:
      DATABASE_TYPE: mongodb
      DATABASE_URL: mongodb://root:root@host.docker.internal:27017
