version: '3.8'

services:

  surrealdb:
      image: surrealdb/surrealdb:latest
      container_name: surrealdb
      ports:
        - "8000:8000"
      restart: always
      command: 
        - start
        - --user=root
        - --pass=root
        - memory

volumes:
  data:
