services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_MASTER_KEY: dev
      MEILI_ENV: development
      MEILI_DB_PATH: data:/data.ms
    ports:
      - 7700:7700

volumes:
  data:
