version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: Arkam2004
      MEILI_ENV: development
      MEILI_DB_PATH: /data.ms:/data.ms
    ports:
      - 7700:7700