services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 8070:8080
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://dev:dev@host.docker.internal:5432/authorizer

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
